#!/bin/bash 
# IpAddressesOnly.sh
     
# Version Date        Author   Description
# 1.0     01-AUG-2021 G Slater Initial version

# Extract all of the lines generated by IpInfo.sh that have IP addresses in them
./IpInfo.sh | sed -n '/\(\(1\?[0-9][0-9]\?\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\(1\?[0-9][0-9]\?\|2[0-4][0-9]\|25[0-5]\)/p'

